### ISSUE TITLE
Ticking World Exception Crash 1.20.1

### ISSUE THREAD

**Issue by VOrlando520** [Patbox/polymer#132]
Periodically happens, but usually get a crash with the following stack trace pointing to polymer
https://pastebin.com/fDgpr01Z

**Comment by Patbox** [comment]
The (`eu.pb4.polymer.core.impl.interfaces.MetaConsumer`)[https://github.com/Patbox/polymer/blob/dev/1.21/polymer-core/src/main/java/eu/pb4/polymer/core/impl/interfaces/MetaConsumer.java] class is just an util class that adds extra context to packets, not doing much outside of it. The issue is likely caused by some other mod
