### ISSUE TITLE
Client crash, logs says it's related to polymer & another mod 

### ISSUE THREAD

**Issue by antoni0C0des** [Patbox/polymer#83]
A client unexpectedly crashed, it seems the logs were pointing out to polymer and another mod called Connectivity

Logs: https://mclo.gs/ZnmlhFB

**Comment by antoni0C0des** [comment]
I also reported it here https://github.com/someaddons/connectivity/issues/80

**Comment by Patbox** [comment]
This error is not caused by polymer (or connectivity in that matter).
The crash points to Create mod (so it can be create, it's addon or some other mod that changes rendering).

The Invalid BlockState ID errors are caused by the crash, which puts game into invalid state (makes both disconnect logic and packet reading logic run at the same time, which creates garbage data)

**Comment by antoni0C0des** [comment]
Thanks you, I'll report it to the create devs..
