### ISSUE TITLE
Polymer Items invisible in Shulker Box tooltip and preview

### ISSUE THREAD

**Issue by borisshoes** [Patbox/polymer#92]
Using a mod like tweakeroo to preview the items in a shulker box ends up having all polymer items invisible.

Would it be possible to mixin when sending the client a shulker box item data to replace the item ids of the polymer items in the box to their vanilla representations?

**Comment by haykam821** [comment]
The issue seems to also affect vanilla, as a shulker box containing only Polymer items will display 'Empty' in its tooltip.

This issue seems to be caused by Polymer only modifying the `Items` list, which works for bundles, not the `BlockEntityTag.Items` list:

https://github.com/Patbox/polymer/blob/1f7c7cba95fe0fe5b484169f50e8bfdc87ef2f36/polymer-core/src/main/java/eu/pb4/polymer/core/api/item/PolymerItemUtils.java#L418-L431

If additional support is desired, note that the following fields can also contain item data, but are not displayed to the player in vanilla:

- `BlockEntityTag.RecordItem` for jukeboxes
- `BlockEntityTag.Book` for lecterns
